version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmdrm-security-center:latest
    ports:
      - "100.111.38.9:3000:3000"
    environment:
      NODE_ENV: production
      API_BASE: http://crowdsecapi.bmdrm.com
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
